const fs = require('fs-extra');
const https = require('https');
const path = require('path');
const chalk = require('chalk');

console.log(chalk.blue('🎵 Creating sample media files...\n'));

async function createMediaFiles() {
    try {
        // Ensure media directory exists
        await fs.ensureDir('./media');
        
        // Create sample music file (silent MP3)
        console.log(chalk.cyan('🎵 Creating music.mp3...'));
        const musicPath = './media/music.mp3';
        
        // Create a simple silent MP3 (base64 encoded minimal MP3)
        const silentMP3 = Buffer.from([
            0xFF, 0xFB, 0x90, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        ]);
        
        await fs.writeFile(musicPath, silentMP3);
        console.log(chalk.green('✅ music.mp3 created (placeholder)'));
        
        // Create welcome image placeholder
        console.log(chalk.cyan('🖼️ Creating welcome.jpg...'));
        const welcomePath = './media/welcome.jpg';
        
        // Create a simple 1x1 pixel JPEG (minimal JPEG header)
        const minimalJPEG = Buffer.from([
            0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46,
            0x00, 0x01, 0x01, 0x01, 0x00, 0x48, 0x00, 0x48, 0x00, 0x00,
            0xFF, 0xC0, 0x00, 0x11, 0x08, 0x00, 0x01, 0x00, 0x01, 0x01,
            0x01, 0x11, 0x00, 0x02, 0x11, 0x01, 0x03, 0x11, 0x01, 0xFF,
            0xC4, 0x00, 0x14, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x08, 0xFF, 0xC4, 0x00, 0x14, 0x10, 0x01, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0xFF, 0xDA, 0x00, 0x0C, 0x03, 0x01, 0x00,
            0x02, 0x11, 0x03, 0x11, 0x00, 0x3F, 0x00, 0x00, 0xFF, 0xD9
        ]);
        
        await fs.writeFile(welcomePath, minimalJPEG);
        console.log(chalk.green('✅ welcome.jpg created (placeholder)'));
        
        // Create README for media folder
        const mediaReadme = `# Media Files

## 📁 Required Files

### music.mp3
- Bot background music
- Replace with your preferred music file
- Supported formats: MP3
- Recommended size: < 50MB

### welcome.jpg
- Welcome message image
- Replace with your custom welcome image
- Supported formats: JPG, PNG
- Recommended size: 1080x1920 or 1080x1080

## 🔄 How to Replace

1. Download your preferred music/image files
2. Rename them to exactly:
   - music.mp3 (for music)
   - welcome.jpg (for welcome image)
3. Replace the existing files in this folder
4. Restart your bot

## 💡 Tips

- Keep file sizes reasonable for WhatsApp compatibility
- Use high-quality images for better appearance
- Music will be sent as audio message, not voice note

## 🎵 Commands that use these files:

- \`.music\` - Sends music.mp3
- \`.welcome\` - Sends welcome.jpg with greeting text

---
*Generated by Simple WhatsApp Bot*`;
        
        await fs.writeFile('./media/README.md', mediaReadme);
        console.log(chalk.green('✅ Media README.md created'));
        
        // Create thumb.jpg for bot thumbnail
        console.log(chalk.cyan('📸 Creating thumb.jpg...'));
        await fs.writeFile('./media/thumb.jpg', minimalJPEG);
        console.log(chalk.green('✅ thumb.jpg created (placeholder)'));
        
        console.log(chalk.blue('\n🎉 All media files created successfully!'));
        console.log(chalk.yellow('\n📝 Next steps:'));
        console.log(chalk.white('1. Replace media/music.mp3 with your preferred music'));
        console.log(chalk.white('2. Replace media/welcome.jpg with your welcome image'));
        console.log(chalk.white('3. Replace media/thumb.jpg with your bot thumbnail'));
        console.log(chalk.white('4. Test with .music and .welcome commands\n'));
        
    } catch (error) {
        console.error(chalk.red('❌ Error creating media files:'), error);
    }
}

// Run if called directly
if (require.main === module) {
    createMediaFiles();
}

module.exports = { createMediaFiles };
